# Generated by Django 2.1.2 on 2018-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
