# Generated by Django 2.1.2 on 2018-10-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplying_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asp.Hospital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asp.Hospital'),
        ),
    ]
