# Generated by Django 2.1.2 on 2018-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0002_order_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
