# Generated by Django 2.1.2 on 2018-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0005_auto_20181029_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
