# Generated by Django 2.1.2 on 2018-10-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0006_auto_20181029_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_no',
        ),
    ]
