# Generated by Django 2.1.2 on 2018-10-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0006_auto_20181030_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='host_a',
            new_name='hospital_a',
        ),
        migrations.RenameField(
            model_name='distance',
            old_name='host_b',
            new_name='hospital_b',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='time_queued_processing',
        ),
        migrations.AddField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_dispatched',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_processing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_queued_dispatch',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QFP', 'Queued for Processing'), ('PBW', 'Processing by Warehouse'), ('QFD', 'Queued for Dispatch'), ('DSD', 'Dispatched'), ('DLD', 'Delivered')], default='QFP', max_length=3),
        ),
    ]
