# Generated by Django 2.1.2 on 2018-10-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0008_auto_20181031_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Available_Items',
            new_name='Available_Item',
        ),
    ]
