# Generated by Django 2.1.2 on 2018-10-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0009_auto_20181031_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asp.Item'),
        ),
    ]
